services:
  - type: web
    name: shortvideo-resolver
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: API_KEY
        value: 299145bbcefca5e3dd0f193dc6d187b0
    plan: free
    healthCheckPath: /health
